openapi: 3.0.0
info:
  title: Ocio API
  description: API for emergencies communication and users management. 
  version: 1.2.1
servers:
  - url: https://localhost:5000/api
    description: Localhost
  - url: https://ocio-backend.onrender.com/api
    description: Main backend deployment
  - url: https://ocio-frontend.onrender.com
    description: Main frontend deployment

paths:
  /login:
    post:
      summary: Sends a request for the JWT
      requestBody:
        description: User's credentials
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: JWT generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT for authentication
        '404':
          description: User not found
        '401':
          description: Wrong credentials
        '500':
          description: Error in token creation
      tags:
        - Login
  
  /emergencies:
    get:
      summary: Gets the list of the emergencies (in progress and ended), with the possibility to filter them
      parameters:
        - name: state
          in: query
          description: Filter for the state of the emergencies
          required: false
          schema:
            type: string
            enum: [In corso, Terminato]
      responses:
        '200':
          description: (Filtered) list of the emergencies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Emergency'
        '500':
          description: Error in emergencies recovery
      tags:
        - Emergencies

    post:
      summary: Creates a new emergency
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Emergency'
      responses:
        '201':
          description: Emergency created. Link in the Location header
          headers:
            Location:
              description: Link to the new emergency
              style: simple
              explode: false
              schema:
                type: string
        '400':
          description: Error in emergency creation
      tags:
        - Emergencies

  /emergencies/{id}:
    get:
      summary: Gets a single emergency
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Details of the emergency
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Emergency'
        '404':
          description: Emergency not found
        '500':
          description: Error in emergency recovery
      tags:
        - Emergencies

    put:
      summary: Updates the details of an emergency
      security:
        - bearerAuth: []      
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Emergency'
      responses:
        '200':
          description: Emergency updated successfully
        '404':
          description: Emergency not found 
        '400':
          description: Error in emergency update
      tags:
        - Emergencies

    delete:
      summary: Deletes an emergency
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Emergency deleted successfully
        '404':
          description: Emergency not found
        '500':
          description: Error in emergency deletion
      tags:
        - Emergencies

  /users:
    get:
      summary: Get a list of all the users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of the users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '500':
          description: Error in users recovery
      tags:
        - Users

    post:
      summary: Creates a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created. Link in the Location header
          headers:
            Location:
              description: Link to the new user
              style: simple
              explode: false
              schema:
                type: string
        '400':
          description: Error in user creation
      tags:
        - Users

  /users/{id}:
    get:
      summary: Gets a single user
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Details of the user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
        '400':
          description: Error in user recovery
      tags:
        - Users

    delete:
      summary: Deletes a user
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: User deleted successfully
        '404':
          description: User not found
        '500':
          description: Error in user deletion
      tags:
        - Users

  /users/{id}/password:
    put:
      summary: Updates the password of a user
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                oldPassword:
                  type: string
                newPassword:
                  type: string
      responses:
        '200':
          description: Password updated successfully
        '404':
          description: User not found
        '400':
          description: Incorrect old password
        '403':
          description: You cannot change another user's password
        '500':
          description: Server error
      tags:
        - Users
  
  /reports:
    get:
      summary: Retrieve all reports
      security: 
        - bearerAuth: []
      responses:
        '200':
          description: List of the reports
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Report'
        '500':
          description: Error in reports recovery
      tags:
        - Reports

    post:
      summary: Creates a new report
      security:
        - bearerAuth: []      
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Report'
      responses:
        '201':
          description: Report created. Link in the Location header
          headers:
            Location:
              description: Link to the new report
              style: simple
              explode: false
              schema:
                type: string
        '400':
          description: Error in report creation
      tags:
        - Reports

  /reports/{id}:
    get:
      summary: Gets a single report
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Details of the report
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Report'
        '404':
          description: Report not found
        '500':
          description: Error in report recovery
      tags:
        - Reports

    put:
      summary: Updates a report
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Report'
      responses:
        '200':
          description: Report updated successfully
        '404':
          description: Report not found
        '400':
          description: Error in report update
      tags:
        - Reports

    delete:
      summary: Deletes a report
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Report deleted successfully
        '404':
          description: Report not found
        '500':
          description: Error in report deletion
      tags:
        - Reports

  /reports/myReports:
    get:
      summary: Retrieve all reports created by the user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of the reports
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Report'
        '500':
          description: Error in reports recovery
      tags:
        - Reports

components:
  schemas:
    User:
      type: object
      required:
        - id
        - email
        - password
      properties:
        id:
          type: string
          description: ID of the user
          example: "65f4b8a1d2e3a5b6c7f8d7w1"
        email:
          type: string
          description: Email of the user
          example: "mario.rossi@gmail.com"
        password:
          type: string
          description: Password of the user
          example: "password123"

    Emergency:
      type: object
      required:
        - id
        - title
        - category
        - startDate
        - location
        - state
      properties:
        id:
          type: string
          description: ID of the emergency
          example: "65f4b8a1d2e3a5b6c7f8d3a8"
        title:
          type: string
          description: Title of the emergency
          example: "Alluvione del sottopassaggio"
        category:
          type: string
          enum: [frana, alluvione, ghiaccio, crollo_strutturale, incendio, neve, tempesta, caduta_albero]
          description: Category of the emergency
          example: "frana"
        startDate:
          type: string
          format: date-time
          description: Timestamp indicating when the emergency started
          example: "2024-10-26T10:02:00Z"
        endDate:
          type: string
          format: date-time
          description: Timestamp indicating when the emergency finished
          example: "2024-10-26T15:30:00Z"
        location:
          type: string
          description: Location of the emergency
          example: "Via Sommarive 9"
        coordinates:
          type: object
          properties:
            lat:
              type: number
              description: Latitude of the emergency location
              example: 46.066422
            lon:
              type: number
              description: Longitude of the emergency location
              example: 11.149765
        state:
          type: string
          enum: [In corso, Terminato]
          default: "In corso"
        description:
          type: string
          description: Description of the emergency
          example: "I forti venti hanno causato la caduta di un albero sulla strada in via Sommarive, la viabilità è stata di conseguenza sospesa temporaneamente."

    Report:
      type: object
      required:
        - id
        - startDate
        - location
        - state
        - description
      properties:
        id:
          type: string
          description: ID of the report
          example: "65f4b8a1d2e3a5b6c7f8d9e0"
        startDate:
          type: string
          format: date-time
          description: Timestamp indicating when the emergency was reported
          example: "2024-10-25T10:00:00Z"
        location:
          type: string
          description: Location of the reported emergency
          example: "Via Sommarive 9"
        coordinates:
          type: object
          properties:
            lat:
              type: number
              description: Latitude of the emergency location
              example: 46.066422
            lon:
              type: number
              description: Longitude of the emergency location
              example: 11.149765
        state:
          type: string
          enum: [pending, approved, rejected]
          default: "pending"
        description:
          type: string
          description: Description of the report
          example: "A landslide has partially blocked the road, making it dangerous to drive."
        createdBy:
          type: string
          format: uuid
          description: "ID of the reporting user"
          example: "65b23f18d4f1c3e58a9a7c12"
  
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT